# NumPy tutorial

Can be found on [youtube](https://www.youtube.com/watch?v=GB9ByFAIAH4&t=823s)

## Load in NumPy

In [13]:
import numpy as np

## The Basics

In [16]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [26]:
# Get Dimension
print(a.ndim, "and", b.ndim)

1 and 2


In [27]:
# Get Shape
print(a.shape, "+", b.shape)

(3,) + (2, 3)


In [28]:
# Get Type
a.dtype

dtype('int32')

In [31]:
# You can also specify a type like this
a = np.array([1,2,3], dtype='int16')
a.dtype

dtype('int16')

In [32]:
# Get size
a.itemsize

2

In [33]:
# Get number of elements
a.size

3

In [35]:
# Get total size
print(a.size * a.itemsize, "is the same as", a.nbytes)

6 is the same as 6


## Accessing/Changing specific elements, rows, columns, etc.

In [38]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a, a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] (2, 7)


In [40]:
# Get a specific element [row, column] (start at 0)
a[1, 5], a[1,-2]

(13, 13)

In [42]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [46]:
# Getting a little more fance [startindex:endindex:stepsize]
a[0,1:6:2], a[0,1:-1:2]

(array([2, 4, 6]), array([2, 4, 6]))

In [48]:
# Change something
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [49]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [53]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b, b[0,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 2


In [52]:
# Get specific element (work outside in) (matrix, row, column)
b[:,0,:]

array([[1, 2],
       [5, 6]])

## Initializing Different Types of Arrays

In [54]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [57]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [58]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [61]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.42505486, 0.3836223 ],
       [0.34852303, 0.62254651],
       [0.97220221, 0.502551  ],
       [0.68034398, 0.20572868]])

In [63]:
np.random.random_sample(a.shape)

array([[0.12397453, 0.0407718 , 0.43189872, 0.02765126, 0.7320199 ,
        0.77101747, 0.81129422],
       [0.78207247, 0.67317603, 0.25923067, 0.05844951, 0.11551867,
        0.24646489, 0.09179794]])

In [66]:
# Random Integer values
np.random.randint(-4,7, size=(3,3))

array([[ 0,  0, -1],
       [ 0,  5,  6],
       [ 2, -1,  6]])

In [67]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [79]:
test = np.ones((5,5))
test[1:4,1:4] = 0
test[2,2] = 9
print(test)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [83]:
# better solution
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [85]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [86]:
# this is fine, but now:
b[0] = 100
print(a, b)

[100   2   3] [100   2   3]


In [88]:
# writing b = a results in numpy pointing to the same values for a and b!
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a, b)

[1 2 3] [100   2   3]


In [89]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [90]:
a + 2

array([3, 4, 5, 6])

In [91]:
a - 2

array([-1,  0,  1,  2])

In [92]:
a * 2

array([2, 4, 6, 8])

In [93]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [94]:
a += 2
a

array([3, 4, 5, 6])

In [95]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [96]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [97]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [98]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

## Linear Algebra

In [103]:
a = np.ones((2,3))

b = np.full((3,2),2)

# a*b does not work because the matrices are different sizes
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [104]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [105]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statistics

In [107]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
np.min(stats)

1

In [110]:
np.max(stats, axis=0)

array([4, 5, 6])

In [111]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [113]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1)) # has to have the same number of elements
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [114]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2]) # sizes also have to match

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
# Horizontal stack
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Miscellaneous

### Load Data from file

(_can also be done with pandas_)

In [122]:
# filedata = np.genfromtxt('data.txt', delimiter=',') would work if you have a file called data.txt
# this will also set the numbers as float type, to prevent this use
# filedata = filedata.astype('int32')
filedata = np.array([[1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5],[3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12],[1,22,33,11,999,11,2,1,78,0,1,2,9,7,1,76,88,2]])
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          7,   1,  76,  88,   2]])

### Boolean Masking and Advanced Indexing

In [ ]:
filedata